"""bd

Revision ID: 3a86c6c2e9f0
Revises: ff4a18f009ce
Create Date: 2023-06-22 20:51:40.594819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a86c6c2e9f0'
down_revision = 'ff4a18f009ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'cover_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('id', table_name='books')
    op.create_unique_constraint(op.f('uq_books_cover_id'), 'books', ['cover_id'])
    op.drop_constraint('books_covers_id_fk', 'books', type_='foreignkey')
    op.create_foreign_key(op.f('fk_books_cover_id_covers'), 'books', 'covers', ['cover_id'], ['id'], ondelete='CASCADE')
    op.drop_index('id', table_name='covers')
    op.create_unique_constraint(op.f('uq_covers_md5_hash'), 'covers', ['md5_hash'])
    op.drop_index('id', table_name='review_statuses')
    op.alter_column('reviews', 'review_status_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'review_status_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index('id', 'review_statuses', ['id'], unique=False)
    op.drop_constraint(op.f('uq_covers_md5_hash'), 'covers', type_='unique')
    op.create_index('id', 'covers', ['id'], unique=False)
    op.drop_constraint(op.f('fk_books_cover_id_covers'), 'books', type_='foreignkey')
    op.create_foreign_key('books_covers_id_fk', 'books', 'covers', ['cover_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('uq_books_cover_id'), 'books', type_='unique')
    op.create_index('id', 'books', ['id'], unique=False)
    op.alter_column('books', 'cover_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
